### ISSUE TITLE
CanvasGradient.addColorStop: Invalid color prevents Graph from being drawn

### ISSUE THREAD

**Issue by Akinetopsia1** [mawinkler/astroweather-card#17]
Both HA and Astroweather are the latest versions, Graphs can't be drawn. Developer tools show this error:

![image](https://github.com/mawinkler/astroweather-card/assets/106173717/16772527-83ce-433f-bd24-e1e707492389)

**Comment by mawinkler** [comment]
I believe that this was caused by a broken config flow which is hopefully fixed with the latest release 0.42.1.

**Comment by Akinetopsia1** [comment]
loaded 0.42.1 and i still get a similar error but now on line 564 of astroweather-card.js 

![image](https://github.com/mawinkler/astroweather-card/assets/106173717/01eca960-2580-4890-bcaa-e9f26d14a3a7)

**Comment by mawinkler** [comment]
Please verify the card's config, if it is similar to the config in the [README](https://github.com/mawinkler/astroweather-card?tab=readme-ov-file#configuration). It can be, that the config flow error which I fixed yesterday messed up your config.

**Comment by Akinetopsia1** [comment]
Ah, as i'm using the default system theme colors i never specified graph colors in the card config. I've had astroweather installed for over a year, the graph used to be white.

Adding the suggested config lines from the readme i had other errors (see below) and the graph still did not display. However toggling each line on and off via the card config made the lines finally appear.

the new error i get repeatedly is 

**In: secondaryinfo-entity-row.js:39:68**
```
Uncaught (in promise) TypeError: this._wrappedElement.shadowRoot.querySelector(...).shadowRoot is null
    _updateElement secondaryinfo-entity-row.js:39
    async*set hass secondaryinfo-entity-row.js:22
    value hui-entities-card.ts:307
    value card-mod.js:1
    i card-mod.js:1
    value hui-entities-card.ts:223
    value hui-entities-card.ts:222
    update lit-element.ts:160
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    ...
 ```

Removing the card gets rid of the errors.

Let me know if i can provide any other information

**Comment by mawinkler** [comment]
In theory, default values for the colors should have been created in the config. I need to double-check this.
Are you now seeing the graph?

**Comment by Akinetopsia1** [comment]
> In theory, default values for the colors should have been created in the config. I need to double-check this. Are you now seeing the graph?

Yes, the graph is showing now. I now have other script errors from a null shadowRoot, but did not have the time to investigate that one.

I don;t think they are related to astroweather.

**Comment by Akinetopsia1** [comment]
Confirmed that the shadowRoot error is unrelated.

Thanks @mawinkler, everything has been working fine since!
